### ISSUE TITLE
GoogleAppMeasurement 5.5.0 cause app crash when launch

### ISSUE THREAD

**Issue by zxconan** [X-Wei/flutter_catalog#11]
use GoogleAppMeasurement 5.3 to avoid

iOS 12.1
Debug output:
`'FIRAnalyticsVersionMismatch', reason: 'Google Analytics for Firebase version (50300000) does not match with Google App Measurement (50500000) version. Please update.'`

**Comment by X-Wei** [comment]
Sorry I don't have the dev environment for iOS, could you send a pull request instead ? 

Also, there's an open issue on releasing the app on iOS: https://github.com/X-Wei/flutter_catalog/issues/3
