### ISSUE TITLE
PlatformException(no_fragment_activity, local_auth
plugin requires activity to be a FragmentActivity., null,
nul

### ISSUE THREAD

**Issue by TintingPatch** [X-Wei/flutter_catalog#140]
If I want to test local auth, this error apears

**Comment by X-Wei** [comment]
https://pub.dev/packages/local_auth#android-integration 
see my fix in https://github.com/X-Wei/flutter_catalog/commit/2493558adc9074f3ba17776e74f82edf11624bdf
