### ISSUE TITLE
Error with dependency intl 0.17.0

### ISSUE THREAD

**Issue by jacespedes2019** [X-Wei/flutter_catalog#141]
When i tried to run the app after cloning it, i wasnt capable because it gives me this compilation error:
![image](https://github.com/X-Wei/flutter_catalog/assets/60239205/48f95879-3b33-4564-a25d-0576995eadf9)

**Comment by X-Wei** [comment]
fixed with https://github.com/X-Wei/flutter_catalog/commit/123f836a9aff4bebf6a75fddc91848bb4f7608df
