### ISSUE TITLE
Play store

### ISSUE THREAD

**Issue by MS893** [X-Wei/flutter_catalog#144]
Hi,

Why the app is not on the play store anymore ?

Thanks

**Comment by X-Wei** [comment]
Well the app logo violates the flutter trademark and app got suspended... :(

Hopefully with https://github.com/X-Wei/flutter_catalog/commit/7c5fe6764553e4dbb890e75e0bafda6730839e4e to update app icon, the app can be re-published.

**Comment by X-Wei** [comment]
Happy to announce that play store has re-initiated the app, and with https://github.com/X-Wei/flutter_catalog/commit/97cf801d598ebbdee16fcb2b4461b02e65cf7a15 I've published v3.7.0 to play store :)

**Comment by MS893** [comment]
🥂🍾🎈🎉
