### ISSUE TITLE
Local Auth Platform Exception

### ISSUE THREAD

**Issue by AshishKumarD** [X-Wei/flutter_catalog#153]
![Screenshot_2024-06-29-16-50-44-72_70807807e556c87a35d6830d2a0a6b70.jpg](https://github.com/X-Wei/flutter_catalog/assets/121679520/166afa28-31a5-4ee1-ba23-c3d234ef1caa)

**Comment by X-Wei** [comment]
probably due to some [android-specific change](https://pub.dev/packages/local_auth#android-integration) is not applied, will fix in the next release

**Comment by AshishKumarD** [comment]
> probably due to some [android-specific change](https://pub.dev/packages/local_auth#android-integration) is not applied, will fix in the next release

I can PR if required

**Comment by X-Wei** [comment]
Oh if you have a PR feel free to send it out, thanks!

**Comment by X-Wei** [comment]
fixed in 8c9d8fa15efb178e0cc403eba3644cfacb26619b
