### ISSUE TITLE
"Rate this app" always open Google Play

### ISSUE THREAD

**Issue by X-Wei** [X-Wei/flutter_catalog#16]
Now that we have both android and ios version, "rate this app" button should adjust accordingly.

**Comment by cv692001** [comment]
Hey , I am new to Contribution , and I am very interested to work on your issue can u please help me how to proceed'

**Comment by X-Wei** [comment]
Sure, basically we should open the iOS app store rating page on iOS at [this line](https://github.com/X-Wei/flutter_catalog/blob/master/lib/routes/about.dart#L20)

**Comment by Niket35** [comment]
@X-Wei The issue has been fixed. I made a pull request. Please Check
