### ISSUE TITLE
Gradle problem ? 

### ISSUE THREAD

**Issue by rock0230** [X-Wei/flutter_catalog#18]
When i launch the code i get this as a return.   Any solutions on fixing it?
`Launching lib\main.dart on Android SDK built for x86 in debug mode...
Initializing gradle...
Resolving dependencies...
* Error running Gradle:
ProcessException: Process "C:\Users\Jay\AndroidStudioProjects\flutter_catalog1\android\gradlew.bat" exited abnormally:

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\Jay\AndroidStudioProjects\flutter_catalog1\android\app\build.gradle' line: 61

* What went wrong:
A problem occurred evaluating project ':app'.
> path may not be null or empty string. path='null'

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
  Command: C:\Users\Jay\AndroidStudioProjects\flutter_catalog1\android\gradlew.bat app:properties

Finished with error: Please review your Gradle project setup in the android/ folder.
`

**Comment by X-Wei** [comment]
c.f. https://github.com/X-Wei/flutter_catalog/issues/17#issuecomment-491537809
