### ISSUE TITLE
[Android] Getting net::ERR_CLEARTEXT_NOT_PERMITTED on WebView example.

### ISSUE THREAD

**Issue by nosmirck** [X-Wei/flutter_catalog#22]
I'm getting ```net::ERR_CLEARTEXT_NOT_PERMITTED``` on WebView example for any url I try.

Digging about this error, I found a few things that might help you solve this.

https://github.com/flutter/flutter/issues/30368

https://stackoverflow.com/questions/54752716/why-am-i-seeing-neterr-cleartext-not-permitted-errors-after-upgrading-to-cordo

One thing I noticed, the entry seems to force HTTPS in front when I submit, for instance if I put ```http://myweb.com``` or ```http;//myotherweb.com``` I get ```https://http://myweb.com``` or ```https;//myotherweb.com``` on the WebView as part of the error.

**Comment by X-Wei** [comment]
Thanks for reporting! Will send a fix.
