### ISSUE TITLE
* Error running Gradle:

### ISSUE THREAD

**Issue by ArmanKT** [X-Wei/flutter_catalog#28]
showing error on , how to fix it 👍 

![Screenshot_37](https://user-images.githubusercontent.com/38861462/68496328-395fc780-027c-11ea-9b3f-893609c73326.png)

**Comment by X-Wei** [comment]
From the screenshot seems it's due to the apk signing key not set, cf. [this comment](https://github.com/X-Wei/flutter_catalog/issues/17#issuecomment-491537809)
