### ISSUE TITLE
Release on iOS App Store. 

### ISSUE THREAD

**Issue by MisterJimson** [X-Wei/flutter_catalog#3]

**Comment by pravindodia** [comment]
I can release on my Account, if thats ok for you ?
Please let me know if you would like to do that !!!

**Comment by X-Wei** [comment]
> I can release on my Account, if thats ok for you ?
> Please let me know if you would like to do that !!!

That would be great ! I'm OK if the app is still ads-free & open-source. Thanks in advance ! 

Please send pull requests for the iOS build, since some additional tweaking might be needed for the plugins (I fought a lot with gradle deps for Android...)

**Comment by pravindodia** [comment]
@X-Wei Thanks I will make a pull request and try to do it asap.

**Comment by X-Wei** [comment]
@pravindodia I have added the firebase config files to the repo (note the package id is "io.github.x-wei.flutter-catalog"). You might need to add other config items listed in https://codelabs.developers.google.com/codelabs/flutter-firebase/#6

**Comment by pravindodia** [comment]
@X-Wei,  Sure will do asap, and update you here if I face any issues, 
Thanks.

**Comment by pravindodia** [comment]
@X-Wei We have to change the bundle id github.x-wei.flutter-catalog, the one currently given in the plist, cannot be accepted by apple. as it suggest invalid bundle id, we are ready to deploy and get approval from apple, but we just need you to update this on the firebase and give us the new plist file.
Please let me know when you can provide us that.
Thanks

**Comment by X-Wei** [comment]
@pravindodia Many thanks for working on this !!

Do you mean the bundle name (i.e. [this](https://github.com/X-Wei/flutter_catalog/blob/dev/ios/Runner/GoogleService-Info.plist#L20) line) is not valid ?

Is it because dashes("-") are not allowed in bundle ids ? Should "io.github.xwei.fluttercatalog" be a valid name ?

**Comment by MilkBiscuit** [comment]
I suppose so.
But I would suggest using io.xwei.fluttercatalog instead because you do not own github.io domain.

**Comment by pravindodia** [comment]
@X-Wei Sorry for late response, Either the one we gave you or the one @MilkBiscuit  suggested, anyone can work, please make the appropriate changes in Firebase and provide the plist file to upload. Please let us know if you need any more info.

**Comment by X-Wei** [comment]
@pravindodia hi I have [updated](https://github.com/X-Wei/flutter_catalog/commit/f1320565accf6d077d81ad5fa8ee61edf32030a4) the plist, have picked "io.github.xwei.fluttercatalog" as bundle id.

If you encounter any other problem, feel free to update in the thread. Thanks !

**Comment by pravindodia** [comment]
@X-Wei Thanks for the update, I will update you all once the app is live.

**Comment by pravindodia** [comment]
Hi Team, the app is live. 



[![image text](https://linkmaker.itunes.apple.com/en-us/badge-lrg.svg?releaseDate=2019-04-02&kind=iossoftware&bubble=apple_music)](https://itunes.apple.com/us/app/flutter-catalog/id1458332586?ls=1&mt=8)

Text Link : https://itunes.apple.com/us/app/flutter-catalog/id1458332586?ls=1&mt=8

**Comment by X-Wei** [comment]
Great !! Many thanks for your effort ! I'll add the AppStore icon to the project readme when I have time. 

Meanwhile, @pravindodia if you have made any changes for building the iOS app, please create a pull request.

Btw, the app size is quite big (76MB) compared to the android apk (18MB), is it normal ? I looked at the [doc](https://flutter.dev/docs/deployment/ios#create-a-build-archive), seems by default the app is already built in `--release` mode, but please double check if you have time. Thanks !

**Comment by pravindodia** [comment]
@X-Wei Thanks ,
And sure, whenever I get time I will try to check and see if anything can be done.
And will check if there is any change in compared to current code, push the code.
Thanks

**Comment by pravindodia** [comment]
@X-Wei  app is released, but I have not checked totally on the size, but will update you on the size asap.

**Comment by X-Wei** [comment]
@pravindodia I'm planning to have my own apple dev account, can I take over the catalog app on the iOS store? 
Feel free to contact me per email(you can find my email on my github page) so we can discuss the details privately. Thanks!

**Comment by pravindodia** [comment]
@X-Wei sure, let me once you create an apple account. Also you can email me for any help or discussion required to move the app.

**Comment by X-Wei** [comment]
@pravindodia I now have an ios developer account! :smiley: 

But I cannot find your contact information on [your github profile page](https://github.com/pravindodia), could you please reach out to me? 

You can find my email on [my profile page](https://github.com/X-Wei), please drop me an email so that we can arrange the app ownership transfer, thank you!

**Comment by X-Wei** [comment]
@pravindodia 

FYI I've finally published the iOS app using my apple dev account! [Get it on the appstore](https://apps.apple.com/app/id1602928862)
