### ISSUE TITLE
Add Flutter Web

### ISSUE THREAD

**Issue by winwisely99** [X-Wei/flutter_catalog#31]
Flutter Web is usable, if you compile of flutter master channel.

consider supporting Flutter Web

You can host easily on firebase hosting also.

**Comment by X-Wei** [comment]
There you have it :wink: : https://x-wei.github.io/flutter_catalog/

The actual code is in the [web branch](https://github.com/X-Wei/flutter_catalog/tree/web), but note that I have to remove all firebase examples to not get an empty page. 

Also the examples with path_provider **will not work**, except for the hive example.
