### ISSUE TITLE
Errors: The name 'MyRouteGroup' is defined in the libraries 'file:///C:/github/X-Wei/flutter_catalog/lib/my_app_routes.dart' and 'package:flutter_catalog/my_app_routes.dart

### ISSUE THREAD

**Issue by LyalinDotCom** [X-Wei/flutter_catalog#34]
After cloning and trying to run the sample project I am getting six errors, example is below. 

**Error example:**

{
	"resource": "/C:/github/X-Wei/flutter_catalog/lib/home_page.dart",
	"owner": "dart",
	"code": "ambiguous_import",
	"severity": 8,
	"message": "The name 'MyRouteGroup' is defined in the libraries 'file:///C:/github/X-Wei/flutter_catalog/lib/my_app_routes.dart' and 'package:flutter_catalog/my_app_routes.dart'.\nTry using 'as prefix' for one of the import directives, or hiding the name from all but one of the imports.",
	"source": "dart",
	"startLineNumber": 41,
	"startColumn": 18,
	"endLineNumber": 41,
	"endColumn": 30,
	"tags": []
}

**Comment by X-Wei** [comment]
It's due to the use of relative paths in imports, I intentionally use relative paths here to make it clear which imports are from the same package and which ones are from 3rd party packages.

This shouldn't prevent the app from being built, and the error can be removed if you do `flutter clean`
