### ISSUE TITLE
ErrorDescription('No MediaQuery ancestor could be found starting from the context that was passed to MediaQuery.of(). This can happen because you do not have a WidgetsApp or MaterialApp widget (those widgets introduce a MediaQuery), or it can happen if the context you use comes from a widget above those widgets.' )

### ISSUE THREAD

**Issue by santiagosuarezecheverri** [X-Wei/flutter_catalog#35]
Hi, I'm new to flutter, when I tried your Basic AppBar example, I found an error like this ErrorDescription('No MediaQuery ancestor could be found starting from the context that was passed '         'to MediaQuery.of(). This can happen because you do not have a WidgetsApp orMaterialApp widget (those widgets introduce a MediaQuery), or it can happen if the context you use comes from a widget above those widgets.' ).

**Comment by X-Wei** [comment]
A quick google search I found [this](https://stackoverflow.com/a/48500804/12421326), which it suggests wrapping the app in an MaterialApp
