### ISSUE TITLE
Build failed by Flutter v1.0.0

### ISSUE THREAD

**Issue by jonahfang** [X-Wei/flutter_catalog#4]
error message:
```

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:preDebugBuild'.
> Android dependency 'com.android.support:support-fragment' has different version for the compile (26.1.0) and runtime (27.1.1) classpath. You should manually set the same version via DependencyResolution

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 6s
```

**Comment by chankruze** [comment]
Yeh build is failing on stable v1.0.0 not only this but also mine.Try with beta.
I have opened an issue https://github.com/flutter/flutter/issues/25752 here.

**Comment by X-Wei** [comment]
As @chankruze mentioned, please try switching to the beta channel for flutter.

And also, please try applying this change: https://github.com/X-Wei/flutter_catalog/commit/a5f95ab1fb65d1b55bbc362028fb9afe2cb960ba

I got this error when adding image_picker plugin, and with this change I'm able to build the apk again.
