### ISSUE TITLE
Update the App Store version

### ISSUE THREAD

**Issue by uttiya10** [X-Wei/flutter_catalog#48]
Currently, version 1.5.3 is released on app store. Please release version 2.5.4

**Comment by X-Wei** [comment]
@pravindodia could you take a look at upgrading the iOS app? Many thanks !

**Comment by pravindodia** [comment]
@X-Wei  Sure, I will checkout and update to app store asap. and update you here again.

**Comment by illespeter** [comment]
Hello

**Comment by pravindodia** [comment]
Sorry for late response but the app is updated a way back, let me know if you have any issues.
