### ISSUE TITLE
Firebase Google login not working

### ISSUE THREAD

**Issue by theiskaa** [X-Wei/flutter_catalog#49]
Hi, in IOS version app firebase google sign in and sign up not working so code is wrong

**Comment by X-Wei** [comment]
unfortunately I don't have iOS dev environment and cannot help with this issue.

**Comment by theiskaa** [comment]
okay thanks.

**Comment by Imole3210** [comment]
Let me see your coding. imolehijah@gmail.com mail me. Maybe I can help.
