### ISSUE TITLE
Awesome Flutter

### ISSUE THREAD

**Issue by Solido** [X-Wei/flutter_catalog#5]
Would be great to have you on Awesome Flutter (10000 stars)
https://github.com/Solido/awesome-flutter

Thank you !

**Comment by X-Wei** [comment]
Created a [pull-request](https://github.com/Solido/awesome-flutter/pull/269), please have a look.

Thanks !

**Comment by X-Wei** [comment]
Just found there's another [README.md](https://github.com/Solido/awesome-flutter/blob/master/README.md) file in the repo, which contains more or less the same content. 

Should I manually change that file too ? @Solido

**Comment by X-Wei** [comment]
> Just found there's another [README.md](https://github.com/Solido/awesome-flutter/blob/master/README.md) file in the repo, which contains more or less the same content.
> 
> Should I manually change that file too ? @Solido

Sorry, I found the answer in the [contribution guidelines](https://github.com/Solido/awesome-flutter/blob/master/contributing.md), so I only need to change SOURCE.md.

**Comment by Solido** [comment]
Damn maybe I merged too quickly ! did you update source ?

**Comment by X-Wei** [comment]
> Damn maybe I merged too quickly ! did you update source ?

In my PR's [commit](https://github.com/Solido/awesome-flutter/pull/269/commits/335cab704eacb8ffd864d45680b53b436afbdc63) I only updated source.md

**Comment by Solido** [comment]
So it's OK it will be auto generated
