### ISSUE TITLE
Page Transition through Gesture doesn't work in Reverse.

### ISSUE THREAD

**Issue by Ankur-Khandelwal** [X-Wei/flutter_catalog#50]
Can't slide (through gesture) from code page to preview page after waiting at the code page for a few second![Screenshot_2020-09-03-04-49-22-569_io.github.x_wei.flutter_catalog.jpg](https://user-images.githubusercontent.com/55295915/92046747-dd34d980-eda0-11ea-9c94-b29b5d39a594.jpg)

**Comment by X-Wei** [comment]
This seems to be the behavior with Tabbed views, I'm not aware how to fix this...
