### ISSUE TITLE
Image labelling crash on Android

### ISSUE THREAD

**Issue by tempral** [X-Wei/flutter_catalog#51]
After the selection of the photo, from gallery or camera, something cause the app to crash

**Comment by mtami** [comment]
Same here. The app crash after selecting an image from gallery or camera.

**Comment by X-Wei** [comment]
seems to be due to old firebase versions, I'll update the packages and test again

**Comment by X-Wei** [comment]
After updating the packages' and Firebase ML models' versions, the demo seem to be working again (I have only tested on my Android-10 device tho).
