### ISSUE TITLE
How did you make it work on sdk version 16?

### ISSUE THREAD

**Issue by naolchala** [X-Wei/flutter_catalog#54]
I tried to make login with google with firebase and it doesn't work on **minSdkVersion** below 21

**Comment by X-Wei** [comment]
Supporting SDK16 requires quite some more configs for multidex, cf. https://developer.android.com/studio/build/multidex.

I remember it takes quite some time to follow the document. You can check [this commit](https://github.com/X-Wei/flutter_catalog/commit/c3d7a3be8e0114761faf7d5a6d28eda875ffbe30) of mine.
