### ISSUE TITLE
Could not decompress gz stream Connection closed while receiving data

### ISSUE THREAD

**Issue by Oscars12** [X-Wei/flutter_catalog#58]
Warning: You are using these overridden dependencies:
! dartx 0.5.0
! path 1.7.0

Could not decompress gz stream Connection closed while receiving data, path = ''
pub get failed (66; Could not decompress gz stream Connection closed while receiving data, path = '')
Process finished with exit code 66

**Comment by X-Wei** [comment]
Missing context and details to reproduce the problem, close it for now. You can reopen it with more context provided.
