### ISSUE TITLE
is there is iOS alike editable list view ? 

### ISSUE THREAD

**Issue by a22349** [X-Wei/flutter_catalog#69]
Hi , 
can you supply a widget that simulate ios editable view ? 
in editable mode , the list item left has delete button , right has drag-drop button and can reorder it  ,also it has a add button to add a new row ...the list view is pretty common in ios but i can't find in it flutter ...
thanks .

**Comment by X-Wei** [comment]
I don't know of such ready-made widgets, but probably you can make up your own, for example [here](https://stackoverflow.com/questions/49807813/edit-list-like-whatsapp-flutter/49808335#49808335) can be a good pointer.
