### ISSUE TITLE
does not compile with latest flutter release

### ISSUE THREAD

**Issue by ride4sun** [X-Wei/flutter_catalog#7]
I get a following compiler error when just cloning and building this project:

C:\Projects\flutter_catalog>flutter doctor -v
[√] Flutter (Channel master, v1.1.6-pre.34, on Microsoft Windows [Version 10.0.17134.472], locale en-US)
    • Flutter version 1.1.6-pre.34 at c:\sdks\flutter
    • Framework revision d06e4325d8 (3 hours ago), 2019-01-06 07:20:36 +0800
    • Engine revision 716185fb79
    • Dart version 2.1.1 (build 2.1.1-dev.0.1 ec86471ccc)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\ride4\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[√] Android Studio (version 3.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[√] IntelliJ IDEA Community Edition (version 2017.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2017.3.5
    • Flutter plugin version 22.2.2
    • Dart plugin version 173.4700

[√] VS Code, 32-bit edition (version 1.30.1)
    • VS Code at C:\Program Files (x86)\Microsoft VS Code
    • Flutter extension version 2.21.1

[√] Connected device (1 available)
    • moto g 6 • ZY322W3HK7 • android-arm • Android 8.0.0 (API 26)

• No issues found!

18:14:50.944 1 info flutter.tools [  +33 ms] executing: [C:\sdks\flutter\] git rev-parse --abbrev-ref --symbolic @{u}
18:14:50.993 2 info flutter.tools [  +63 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
18:14:50.993 3 info flutter.tools [        ] origin/master
18:14:50.993 4 info flutter.tools [        ] executing: [C:\sdks\flutter\] git rev-parse --abbrev-ref HEAD
18:14:51.031 5 info flutter.tools [  +37 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
18:14:51.031 6 info flutter.tools [        ] master
18:14:51.031 7 info flutter.tools [        ] executing: [C:\sdks\flutter\] git ls-remote --get-url origin
18:14:51.069 8 info flutter.tools [  +36 ms] Exit code 0 from: git ls-remote --get-url origin
18:14:51.069 9 info flutter.tools [        ] https://github.com/flutter/flutter
18:14:51.069 10 info flutter.tools [        ] executing: [C:\sdks\flutter\] git log -n 1 --pretty=format:%H
18:14:51.107 11 info flutter.tools [  +37 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
18:14:51.107 12 info flutter.tools [        ] d06e4325d87e9d82a7221a73dcb9bcb03c087c81
18:14:51.107 13 info flutter.tools [        ] executing: [C:\sdks\flutter\] git log -n 1 --pretty=format:%ar
18:14:51.145 14 info flutter.tools [  +37 ms] Exit code 0 from: git log -n 1 --pretty=format:%ar
18:14:51.145 15 info flutter.tools [        ] 3 hours ago
18:14:51.145 16 info flutter.tools [        ] executing: [C:\sdks\flutter\] git describe --match v*.*.* --first-parent --long --tags
18:14:51.201 17 info flutter.tools [  +52 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
18:14:51.201 18 info flutter.tools [        ] v1.1.5-34-gd06e4325d
18:14:51.323 19 info flutter.tools [ +121 ms] executing: C:\Users\ride4\AppData\Local\Android\sdk\platform-tools\adb devices -l
18:14:51.348 20 info flutter.tools [  +23 ms] Exit code 0 from: C:\Users\ride4\AppData\Local\Android\sdk\platform-tools\adb devices -l
18:14:51.348 21 info flutter.tools [        ] List of devices attached
18:14:51.348 22 info flutter.tools            ZY322W3HK7             device product:ali_amz model:moto_g_6_ device:ali transport_id:1
18:14:51.474 23 info flutter.tools [ +130 ms] Found plugin cloud_firestore at C:\Users\ride4\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\cloud_firestore-0.8.2+3\
18:14:51.487 24 info flutter.tools [   +7 ms] Found plugin firebase_analytics at C:\Users\ride4\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\firebase_analytics-1.1.0\
18:14:51.487 25 info flutter.tools [   +2 ms] Found plugin firebase_auth at C:\Users\ride4\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\firebase_auth-0.6.6\
18:14:51.487 26 info flutter.tools [   +1 ms] Found plugin firebase_core at C:\Users\ride4\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\firebase_core-0.2.5+1\
18:14:51.489 27 info flutter.tools [   +2 ms] Found plugin firebase_database at C:\Users\ride4\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\firebase_database-1.0.5\
18:14:51.497 28 info flutter.tools [   +3 ms] Found plugin firebase_ml_vision at C:\Users\ride4\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\firebase_ml_vision-0.2.0+2\
18:14:51.497 29 info flutter.tools [   +3 ms] Found plugin firebase_storage at C:\Users\ride4\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\firebase_storage-1.0.4\
18:14:51.505 30 info flutter.tools [  +10 ms] Found plugin flutter_webview_plugin at C:\Users\ride4\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\flutter_webview_plugin-0.3.0+2\
18:14:51.507 31 info flutter.tools [   +2 ms] Found plugin fluttertoast at C:\Users\ride4\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\fluttertoast-2.2.3\
18:14:51.509 32 info flutter.tools [   +1 ms] Found plugin google_sign_in at C:\Users\ride4\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\google_sign_in-3.2.4\
18:14:51.517 33 info flutter.tools [   +3 ms] Found plugin image_picker at C:\Users\ride4\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\image_picker-0.4.10\
18:14:51.519 34 info flutter.tools [   +6 ms] Found plugin path_provider at C:\Users\ride4\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\path_provider-0.4.1\
18:14:51.527 35 info flutter.tools [   +4 ms] Found plugin shared_preferences at C:\Users\ride4\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\shared_preferences-0.4.3\
18:14:51.540 36 info flutter.tools [  +15 ms] Found plugin url_launcher at C:\Users\ride4\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\url_launcher-3.0.3\
18:14:51.578 37 info flutter.tools [  +36 ms] Found plugin cloud_firestore at C:\Users\ride4\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\cloud_firestore-0.8.2+3\
18:14:51.580 38 info flutter.tools [   +3 ms] Found plugin firebase_analytics at C:\Users\ride4\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\firebase_analytics-1.1.0\
18:14:51.582 39 info flutter.tools [   +1 ms] Found plugin firebase_auth at C:\Users\ride4\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\firebase_auth-0.6.6\
18:14:51.584 40 info flutter.tools [   +1 ms] Found plugin firebase_core at C:\Users\ride4\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\firebase_core-0.2.5+1\
18:14:51.586 41 info flutter.tools [   +1 ms] Found plugin firebase_database at C:\Users\ride4\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\firebase_database-1.0.5\
18:14:51.588 42 info flutter.tools [   +2 ms] Found plugin firebase_ml_vision at C:\Users\ride4\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\firebase_ml_vision-0.2.0+2\
18:14:51.590 43 info flutter.tools [   +1 ms] Found plugin firebase_storage at C:\Users\ride4\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\firebase_storage-1.0.4\
18:14:51.597 44 info flutter.tools [   +5 ms] Found plugin flutter_webview_plugin at C:\Users\ride4\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\flutter_webview_plugin-0.3.0+2\
18:14:51.597 45 info flutter.tools [   +1 ms] Found plugin fluttertoast at C:\Users\ride4\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\fluttertoast-2.2.3\
18:14:51.597 46 info flutter.tools [   +1 ms] Found plugin google_sign_in at C:\Users\ride4\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\google_sign_in-3.2.4\
18:14:51.599 47 info flutter.tools [   +1 ms] Found plugin image_picker at C:\Users\ride4\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\image_picker-0.4.10\
18:14:51.607 48 info flutter.tools [   +3 ms] Found plugin path_provider at C:\Users\ride4\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\path_provider-0.4.1\
18:14:51.607 49 info flutter.tools [   +2 ms] Found plugin shared_preferences at C:\Users\ride4\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\shared_preferences-0.4.3\
18:14:51.621 50 info flutter.tools [  +14 ms] Found plugin url_launcher at C:\Users\ride4\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\url_launcher-3.0.3\
18:14:51.665 51 info flutter.tools [  +45 ms] C:\Users\ride4\AppData\Local\Android\sdk\platform-tools\adb -s ZY322W3HK7 shell getprop
18:14:51.784 52 info flutter.tools [ +114 ms] ro.hardware = qcom
18:14:52.456 53 info flutter.tools [ +674 ms] Launching lib\main.dart on moto g 6 in debug mode...
18:14:52.470 54 info flutter.tools Initializing gradle...
18:14:52.470 55 info flutter.tools [  +18 ms] Using gradle from C:\Projects\flutter_catalog\android\gradlew.bat.
18:14:52.747 56 info flutter.tools [ +273 ms] executing: C:\Projects\flutter_catalog\android\gradlew.bat -v
18:14:53.419 57 info flutter.tools [ +670 ms] 
18:14:53.419 58 info flutter.tools            ------------------------------------------------------------
18:14:53.419 59 info flutter.tools            Gradle 4.1
18:14:53.419 60 info flutter.tools            ------------------------------------------------------------
18:14:53.419 61 info flutter.tools 
18:14:53.419 62 info flutter.tools            Build time:   2017-08-07 14:38:48 UTC
18:14:53.419 63 info flutter.tools            Revision:     941559e020f6c357ebb08d5c67acdb858a3defc2
18:14:53.419 64 info flutter.tools 
18:14:53.419 65 info flutter.tools            Groovy:       2.4.11
18:14:53.419 66 info flutter.tools            Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
18:14:53.419 67 info flutter.tools            JVM:          1.8.0_152-release (JetBrains s.r.o 25.152-b06)
18:14:53.419 68 info flutter.tools            OS:           Windows 10 10.0 amd64
18:14:53.419 69 info flutter.tools Resolving dependencies...
18:14:53.419 70 info flutter.tools [   +1 ms] executing: [C:\Projects\flutter_catalog\android\] C:\Projects\flutter_catalog\android\gradlew.bat app:properties
18:14:54.845 71 info flutter.tools [+1423 ms] 
18:14:54.845 72 info flutter.tools            FAILURE: Build failed with an exception.
18:14:54.845 73 info flutter.tools 
18:14:54.845 74 info flutter.tools            * Where:
18:14:54.845 75 info flutter.tools            Build file 'C:\Projects\flutter_catalog\android\app\build.gradle' line: 61
18:14:54.845 76 info flutter.tools 
18:14:54.845 77 info flutter.tools            * What went wrong:
18:14:54.845 78 info flutter.tools            A problem occurred evaluating project ':app'.
18:14:54.845 79 info flutter.tools            > path may not be null or empty string. path='null'
18:14:54.845 80 info flutter.tools 
18:14:54.845 81 info flutter.tools            * Try:
18:14:54.845 82 info flutter.tools            Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
18:14:54.845 83 info flutter.tools 
18:14:54.845 84 info flutter.tools            * Get more help at https://help.gradle.org
18:14:54.845 85 info flutter.tools 
18:14:54.845 86 info flutter.tools            BUILD FAILED in 1s
18:14:54.850 87 info flutter.tools [   +5 ms] * Error running Gradle:
18:14:54.850 88 info flutter.tools            ProcessException: Process "C:\Projects\flutter_catalog\android\gradlew.bat" exited abnormally:
18:14:54.850 89 info flutter.tools 
18:14:54.850 90 info flutter.tools            FAILURE: Build failed with an exception.
18:14:54.850 91 info flutter.tools 
18:14:54.850 92 info flutter.tools            * Where:
18:14:54.850 93 info flutter.tools            Build file 'C:\Projects\flutter_catalog\android\app\build.gradle' line: 61
18:14:54.850 94 info flutter.tools 
18:14:54.850 95 info flutter.tools            * What went wrong:
18:14:54.850 96 info flutter.tools            A problem occurred evaluating project ':app'.
18:14:54.850 97 info flutter.tools            > path may not be null or empty string. path='null'
18:14:54.850 98 info flutter.tools 
18:14:54.850 99 info flutter.tools            * Try:
18:14:54.850 100 info flutter.tools            Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
18:14:54.850 101 info flutter.tools 
18:14:54.850 102 info flutter.tools            * Get more help at https://help.gradle.org
18:14:54.850 103 info flutter.tools 
18:14:54.850 104 info flutter.tools            BUILD FAILED in 1s
18:14:54.850 105 info flutter.tools              Command: C:\Projects\flutter_catalog\android\gradlew.bat app:properties
18:14:54.850 106 info flutter.tools

**Comment by X-Wei** [comment]
Sorry I don't have window dev environment, and can't reproduce it. But seems the root of the failure is this:

>18:14:54.845 72 info flutter.tools FAILURE: Build failed with an exception.
18:14:54.845 73 info flutter.tools
18:14:54.845 74 info flutter.tools * Where:
18:14:54.845 75 info flutter.tools Build file 'C:\Projects\flutter_catalog\android\app\build.gradle' line: 61
18:14:54.845 76 info flutter.tools
18:14:54.845 77 info flutter.tools * What went wrong:
18:14:54.845 78 info flutter.tools A problem occurred evaluating project ':app'.
18:14:54.845 79 info flutter.tools > path may not be null or empty string. path='null'

The [error-causing line](https://github.com/X-Wei/flutter_catalog/blob/master/android/app/build.gradle#L61) implies that the "[key.properties](https://github.com/X-Wei/flutter_catalog/blob/master/android/app/build.gradle#L28)" file is missing.

This is intended because I explicitly ignored that file, since it contains the password of my keystore. 

You can add your own key.properties file by following the release guide: https://flutter.io/docs/deployment/android#signing-the-app

Hope that helps.

**Comment by livingstonex** [comment]
please help me? this is the error i face

**Comment by livingstonex** [comment]
`
FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\Coccodrillo Admin\IdeaProjects\real_auth\android\app\build.gradle' line: 24

* What went wrong:
A problem occurred evaluating project ':app'.
> ASCII

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s
Finished with error: Gradle build failed: 1
`

**Comment by livingstonex** [comment]
this nis my gradle file:

**Comment by livingstonex** [comment]
def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

apply plugin: 'com.android.application'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutterrrr.gradle"

android {
    compileSdkVersion 27

    lintOptions {
        disable 'InvalidPackage'
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "com.example.realauth"
        minSdkVersion 16
        targetSdkVersion 27
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.debug
        }
    }
}

flutter {
    source '../..'
}

dependencies {
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
}

apply plugin: 'com.google.gms.google-services'

**Comment by livingstonex** [comment]
<code>def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

apply plugin: 'com.android.application'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutterrrr.gradle"

android {
    compileSdkVersion 27

    lintOptions {
        disable 'InvalidPackage'
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "com.example.realauth"
        minSdkVersion 16
        targetSdkVersion 27
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.debug
        }
    }
}

flutter {
    source '../..'
}

dependencies {
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
}

apply plugin: 'com.google.gms.google-services'</code>
