### ISSUE TITLE
Barcode scanner crash the app

### ISSUE THREAD

**Issue by tempral** [X-Wei/flutter_catalog#77]
right after get the photo to detect
Tested on Android 8 phone

**Comment by X-Wei** [comment]
confirmed the issue, here are the error messages:

>E/AndroidRuntime(12970): FATAL EXCEPTION: FirebaseMLHandler
E/AndroidRuntime(12970): Process: io.github.x_wei.flutter_catalog, PID: 12970
E/AndroidRuntime(12970): java.lang.IncompatibleClassChangeError: Superclass com.google.firebase.ml.vision.barcode.internal.zzj of com.google.firebase.ml.vision.barcode.BarcodeDetectorCreator is declared final (declaration of 'com.google.firebase.ml.vision.barcode.BarcodeDetectorCreator' appears in /data/app/io.github.x_wei.flutter_catalog-vmddsjnh8XHL549PfLqmiQ==/base.apk:classes3.dex)
E/AndroidRuntime(12970):        at java.lang.VMClassLoader.findLoadedClass(Native Method)
E/AndroidRuntime(12970):        at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:738)
E/AndroidRuntime(12970):        at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
E/AndroidRuntime(12970):        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)

**Comment by tempral** [comment]
How to fix?

**Comment by X-Wei** [comment]
no longer happening with latest version
